# Generated by Django 3.2.15 on 2022-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShmotAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media', verbose_name='Шмотье')),
                ('sex', models.CharField(max_length=20, verbose_name='Пол')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата выстовки')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
